# 1. Import the numpy package under the name np

In [1]:
import numpy as np

# 2. Print the numpy version and the configuration

In [5]:
print(np.__version__)
print(np.show_config())

1.23.2
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

# 3. Create a null vector of size 10

In [8]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4. How to find the memory size of any array

In [9]:
memory_size = z.nbytes
print(memory_size)

80


# 5. How to get the documentation of the numpy add function from the command line?

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 6. Create a null vector of size 10 but the fifth value which is 1

In [11]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Create a vector with values ranging from 10 to 49

In [13]:
ten_to_fortyNine = np.arange(10,50)
print(ten_to_fortyNine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last) 

In [15]:
reverse_vector = np.flip(ten_to_fortyNine)
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
three_by_three = np.arange(0,9).reshape(3,3)
print(three_by_three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [21]:
array = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(array)
print(non_zero)

(array([0, 1, 4], dtype=int64),)


# 11. Create a 3x3 identity matrix

In [25]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12. Create a 3x3x3 array with random values 

In [27]:
np.random.random((3,3,3))

array([[[0.48110557, 0.29261087, 0.78432809],
        [0.74633228, 0.85288249, 0.93555329],
        [0.38001367, 0.84281343, 0.42539989]],

       [[0.70078562, 0.55309839, 0.28332946],
        [0.27519233, 0.56300047, 0.05676384],
        [0.48887526, 0.07011559, 0.64005204]],

       [[0.1849602 , 0.33455027, 0.99225205],
        [0.0512567 , 0.58751257, 0.98818807],
        [0.61046445, 0.60228969, 0.62199884]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [36]:
ten_by_ten = np.random.random((10, 10))
max_value = np.max(ten_by_ten)
min_value = np.min(ten_by_ten)
print(ten_by_ten)
print(max_value)
print(min_value)

[[0.01786827 0.27604607 0.07087041 0.10036027 0.39441977 0.8505041
  0.06264553 0.99214928 0.59455225 0.46654902]
 [0.62784494 0.80006393 0.93983277 0.53578244 0.68928674 0.0875203
  0.82363686 0.74939145 0.60901065 0.01300199]
 [0.70189063 0.04252294 0.96340207 0.57899285 0.2793757  0.6143443
  0.87406577 0.77159549 0.23961241 0.62621035]
 [0.64872284 0.20715812 0.5299704  0.29019675 0.18658973 0.409253
  0.63849708 0.4560022  0.43071118 0.44964774]
 [0.61894995 0.98641431 0.12840877 0.0871217  0.14236365 0.35562684
  0.17566648 0.55288131 0.82546175 0.35211077]
 [0.5027456  0.97898604 0.00898726 0.49067079 0.11752853 0.81866339
  0.5760162  0.95851999 0.51792043 0.09693153]
 [0.36757125 0.10855209 0.69970125 0.77929957 0.53155255 0.04684161
  0.1782209  0.02542302 0.20872704 0.29825768]
 [0.30756614 0.47044396 0.02350344 0.83435749 0.66263424 0.5344569
  0.22216151 0.56392157 0.29484754 0.09245421]
 [0.45794484 0.26079322 0.62501765 0.59963745 0.12342746 0.08640163
  0.45077472 0.065

# 14. Create a random vector of size 30 and find the mean value

In [37]:
random_vector = np.random.random((30))
mean_value = np.mean(random_vector)
print(mean_value)

0.4117276875682093


# 15. Create a 2d array with 1 on the border and 0 inside

In [42]:
two_dimension_array = np.ones((5,5))
two_dimension_array[1:-1, 1:-1] = 0
print(two_dimension_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 16. How to add a border (filled with 0's) around an existing array?

In [48]:
array = np.ones((5,5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 17. What is the result of the following expression?

In [49]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [51]:
0 * np.nan

nan

In [52]:
np.nan == np.nan

False

In [54]:
np.inf > np.nan

False

In [55]:
np.nan - np.nan

nan

In [56]:
np.nan in set([np.nan])

True

In [57]:
0.3 == 3 * 0.1

False

# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [59]:
matrix = np.eye(4)
matrix[1][1] = 2
matrix[2][2] = 3
matrix[3][3] = 4
print(matrix)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [68]:
matrix = np.ones((8,8))
matrix[::2,::2] = 0
matrix[1::2,1::2] = 0
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [69]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


# 21. Create a checkerboard 8x8 matrix using the tile function

In [73]:
a = np.array([[0,1],[1,0]])
np.tile(a, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 22. Normalize a 5x5 random matrix

In [77]:
arr =np.random.random((5,5))
normalized_vector = arr / np.linalg.norm(arr)
print(normalized_vector)

[[0.08946349 0.27115303 0.29884955 0.09530989 0.05831266]
 [0.26804389 0.00090918 0.1742909  0.0887142  0.07831682]
 [0.27062879 0.32428792 0.05428729 0.2944791  0.11046896]
 [0.22264572 0.32411593 0.16189476 0.29454348 0.03951208]
 [0.25492852 0.03544533 0.1938748  0.13645073 0.16904464]]


# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [7]:
rgba_color = np.dtype([("r", np.ubyte),
                      ("g", np.ubyte),
                      ("b", np.ubyte),
                      ("a", np.ubyte)])
print(rgba_color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [3]:
np.dtype("i4, (2,3)f8, f4")

dtype([('f0', '<i4'), ('f1', '<f8', (2, 3)), ('f2', '<f4')])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [9]:
matrix_1 = np.ones((5,3))
matrix_2 = np.full((3,2),5)
multi = np.dot(matrix_1, matrix_2)
print(multi)

[[15. 15.]
 [15. 15.]
 [15. 15.]
 [15. 15.]
 [15. 15.]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [12]:
array = np.arange(10)
array = np.where((array>3) & (array<8), array*(-1), array)
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


# 26. What is the output of the following script?
Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [13]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27. Consider an integer vector Z, which of these expressions are legal? 


In [18]:
Z = np.arange((9))
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[       1        1        4       27      256     3125    46656   823543
 16777216]
[  0   1   2   4   8  16  32  64 128]
[False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


# 28. What are the result of the following expressions?

In [20]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\User\AppData\Local\Temp\ipykernel_18348\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_18348\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


# 29. How to round away from zero a float array ? 

In [21]:
array = np.array([32.11, 51.5, 0.112])
array = np.round(array)
print(array)

[32. 52.  0.]


# 30. How to find common values between two arrays?

In [23]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40, 50, 60])
common_values = np.intersect1d(array1, array2)
print(common_values)

[10 40 60]


# 31. How to ignore all numpy warnings (not recommended)?

In [24]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

# 32. Is the following expressions true? 

In [25]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

# 33. How to get the dates of yesterday, today and tomorrow?

In [35]:
print("Yesterday = ",np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print("Today = ",np.datetime64('today', 'D'))
print("Tomorrow = ",np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

Yesterday =  2022-10-12
Today =  2022-10-13
Tomorrow =  2022-10-14


# 34. How to get all the dates corresponding to the month of July 2016?

In [42]:
all_date = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(all_date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [43]:
A = np.ones(3)
B = np.ones(3)
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)


array([-1., -1., -1.])

# 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [8]:
array = np.random.uniform(0,10,10)
print(np.floor(array))
print(np.ceil(array)-1)
print(array.astype(int))
print(np.trunc(array))

[8. 4. 3. 5. 7. 1. 2. 0. 5. 3.]
[8. 4. 3. 5. 7. 1. 2. 0. 5. 3.]
[8 4 3 5 7 1 2 0 5 3]
[8. 4. 3. 5. 7. 1. 2. 0. 5. 3.]


# 37.Create a 5x5 matrix with row values ranging from 0 to 4

In [16]:
array = np.zeros((5,5))
array = array+np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 38.Consider a generator function that generates 10 integers and use it to build an array

In [25]:
def generator():
    for i in range(10):
        yield i
array = np.fromiter(generator(),dtype = int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [32]:
np.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

# 40. Create a random vector of size 10 and sort it

In [36]:
array = np.random.random(10)
array = np.sort(array)
print(array)

[0.06364709 0.12127531 0.27147126 0.40243899 0.41765837 0.45778032
 0.50645351 0.53315726 0.64222399 0.78551976]


# 41. How to sum a small array faster than np.sum?

In [39]:
array = np.arange(10)
np.add.reduce(array)

45

# 42. Consider two random array A and B, check if they are equal

In [42]:
A = np.random.random((5))
B = np.random.random((5))
equal_check = np.array_equal(A,B)
print(equal_check)

False


# 43. Make an array immutable (read-only)

In [47]:
a = np.random.random(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [54]:
array = np.random.random((10,2))
x,y = array[:,0], array[:,1]
r = np.sqrt(x**2 + y**2)
print(r)

[0.62007265 0.96700677 0.8426617  0.84642802 0.86652596 1.31963312
 0.94779652 0.73488542 1.22269395 1.10174303]


# 45. Create random vector of size 10 and replace the maximum value by 0

In [69]:
array = np.random.random((10))
array[np.argmax(array)] = 0
print(array)

[0.07639992 0.13562468 0.82807194 0.8965369  0.59801954 0.34656322
 0.04138089 0.30743447 0.25749363 0.52089522]
[0.07639992 0.13562468 0.82807194 0.         0.59801954 0.34656322
 0.04138089 0.30743447 0.25749363 0.52089522]


# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [73]:
array = np.zeros((5,5), [('x', float),('y',float)])
array['x'],array['y'] = np.meshgrid(np.linspace(0,1,5),
                                   np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [6]:
x = np.arange((5))
y = np.ones((5))
c = 1 / np.subtract.outer(x,y)
print(c)

[[-1.         -1.         -1.         -1.         -1.        ]
 [        inf         inf         inf         inf         inf]
 [ 1.          1.          1.          1.          1.        ]
 [ 0.5         0.5         0.5         0.5         0.5       ]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]]


C:\Users\User\AppData\Local\Temp\ipykernel_16404\1792209794.py:3: RuntimeWarning: divide by zero encountered in divide
  c = 1 / np.subtract.outer(x,y)


# 48. Print the minimum and maximum representable value for each numpy scalar type

In [8]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


# 49. How to print all the values of an array? 

In [18]:
np.set_printoptions(threshold=float("inf"))
Z = np.arange((40))
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


# 50. How to find the closest value (to a given scalar) in a vector?

In [26]:
x = np.arange(100)
a = np.random.uniform(0,100)
index = (np.abs(x-a)).argmin()
print(index)

93


# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [35]:
x = np.array([('R', 1.7, 6.0), ('G', 3.9, 5.0), ('G', 8.3, 27.0)],
             dtype=[('color', 'U10'), ('x', 'f4'), ('y', 'f4')])
print(x)

[('R', 1.7,  6.) ('G', 3.9,  5.) ('G', 8.3, 27.)]


# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [41]:
a = np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
distance = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(distance)

[[0.         0.12752883 0.56698997 0.67119281 0.5688444  0.66858822
  0.56704091 0.2349924  0.37930464 0.38732604 0.1404602  0.30796353
  0.56590086 0.26694337 0.52785774 0.30025537 0.31172596 0.86584712
  0.19157461 0.43393629 0.79779053 0.48963496 0.41931663 0.10448921
  0.82917864 0.25246092 0.20401395 0.66299757 0.52902938 0.56850538
  0.31625824 0.84463174 0.18983246 0.58740459 0.30720639 0.42213003
  0.39939456 0.07785479 0.61730278 0.66785159 0.615083   0.17267023
  0.70069449 0.75411807 0.45852731 0.61024169 0.12691991 0.05050395
  0.23510628 0.61690656 0.24147896 0.5294604  0.31483292 0.35725211
  0.72571714 0.82813655 0.8046345  0.49797391 0.32016665 0.36455458
  0.24339201 0.65225036 0.10860839 0.09834183 0.58957358 0.65628372
  0.17892652 0.70358443 0.52495082 0.36741108 0.56203233 0.1537614
  0.44990502 0.6458774  0.38992346 0.74128748 0.58380994 0.1811619
  0.23397941 0.73665785 0.63483677 0.60880105 0.57805228 0.60885204
  0.70972494 0.85092745 0.74630483 0.30531649 0.30

# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [45]:
a = np.ones((5))
print(a.astype(int))

[1 1 1 1 1]


# 54. How to read the following file?

In [48]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
a = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\User\AppData\Local\Temp\ipykernel_16404\2355838675.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.genfromtxt(s, delimiter=",", dtype=np.int)


# 55. What is the equivalent of enumerate for numpy arrays?

In [ ]:
np.nindex(array_name.shape)

# 56.Generate a generic 2D Gaussian-like array

In [52]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
x = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (x-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

# 57. How to randomly place p elements in a 2D array?

In [62]:
n = 5
p = 5
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),3)
print(a)

[[3. 0. 3. 0. 0.]
 [3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]


# 58. Subtract the mean of each row of a matrix 

In [70]:
x = np.arange(15).reshape(5,3)
y = x - x.mean()
print(y)

[[-7. -6. -5.]
 [-4. -3. -2.]
 [-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


# 59. How to sort an array by the nth column? 

In [79]:
a = np.random.random((10,3))
x = a[a[:,2].argsort()]
print(x)

[[0.59390973 0.75225155 0.03287876]
 [0.96002588 0.03148874 0.08664208]
 [0.11667381 0.74181002 0.20256854]
 [0.01538842 0.97444576 0.23905754]
 [0.7936005  0.46875769 0.35441973]
 [0.16985042 0.66062626 0.41021008]
 [0.88469052 0.29021721 0.45970258]
 [0.70565831 0.22351218 0.52542681]
 [0.84440411 0.08896192 0.80404882]
 [0.93176623 0.22477905 0.89634159]]


# 60. How to tell if a given 2D array has null columns?

In [85]:
a = np.random.random((3,10))
print((~a.any(axis=0)).any())

False


# 61. Find the nearest value from a given value in an array

In [106]:
a = .7
b = np.random.uniform(0,1,10)
nv = b.flat[np.abs(a-b).argmin()]
print(nv)

0.7156415507525001


# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [111]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
for i,j,k in np.nditer([a,b, None]):
    c = a + b
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 63. Create an array class that has a name attribute

# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
a = np.array([7, 8, 5, 6, 9, 1])
b = np.arange((len(a)))
np.add.at(a, b, 1)
print(a)

[ 8  9  6  7 10  2]


# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [17]:
a = np.random.random((4,2,2,4))
c = a.sum(axis=(-2,-1))
print(c)

[[3.58496691 5.66127656]
 [4.20456295 4.71906084]
 [4.03414659 5.04232316]
 [5.14046619 2.53603628]]


# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

# 69. How to get the diagonal of a dot product?

In [43]:
a = np.random.randint(1,10,(4,4))
b = np.random.randint(1,10,(4,4))
s = np.diag(np.dot(a,b))
print(s)

[130 229 124 104]


# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [73]:
vector = np.array([1, 2, 3, 4, 5])
a = np.zeros(17)
a[::4] = vector
print(a)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [88]:
a = np.ones((5,5,3))
b = np.ones((5,5))
print(a * b[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# 72. How to swap two rows of an array?

In [95]:
a = np.arange(15).reshape(5,3)
print(a)
print('\n')
a[[2,3]] = a[[3,2]]
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 0  1  2]
 [ 3  4  5]
 [ 9 10 11]
 [ 6  7  8]
 [12 13 14]]


# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [100]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# 75. How to compute averages using a sliding window over an array? 

In [5]:
from numpy.lib.stride_tricks import sliding_window_view

In [109]:
a = np.arange(10)
print(sliding_window_view(a, 3).mean())

4.5


# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [126]:
z= np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


# 77. How to negate a boolean, or to change the sign of a float inplace?

In [129]:
a = np.random.random(10)
print(np.negative(a))

[-0.14541346 -0.30167081 -0.52180418 -0.58159093 -0.19897613 -0.31173242
 -0.69953738 -0.55733968 -0.41168797 -0.07239911]


# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [6]:
x = np.arange(15)
sliding_window_view(x, 3)[::2, :]

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [10, 11, 12],
       [12, 13, 14]])

# 82. Compute a matrix rank

In [8]:
a = np.arange(20).reshape(4,5)
rank = np.linalg.matrix_rank(a)
print(rank)

2


# 83. How to find the most frequent value in an array?

In [14]:
c = np.bincount([1,1,2,3,4,4,4,6])
mfv = c.argmax()
print(mfv)

4


# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [23]:
a = np.random.randint(0,5,(10,10))
print("Random 10X10 matrix:")
print(a)
n = 3
i = 1 + (a.shape[0]-3)
j = 1 + (a.shape[1]-3)
result = np.lib.stride_tricks.as_strided(a, shape=(i, j, n, n), strides = a.strides + a.strides)
print("\nContiguous 3x3 blocks:")
print(result)

Random 10X10 matrix:
[[2 3 4 0 3 0 3 4 4 3]
 [4 1 2 0 4 1 3 1 3 0]
 [0 2 4 0 1 4 4 1 0 4]
 [3 1 0 1 0 0 1 0 4 4]
 [0 1 2 1 1 3 2 0 1 2]
 [4 4 0 2 0 1 1 1 0 1]
 [3 0 2 1 1 2 4 4 0 3]
 [0 2 2 1 2 1 4 0 3 3]
 [3 3 4 2 4 2 1 0 1 1]
 [1 4 3 3 1 0 1 2 1 0]]

Contiguous 3x3 blocks:
[[[[2 3 4]
   [4 1 2]
   [0 2 4]]

  [[3 4 0]
   [1 2 0]
   [2 4 0]]

  [[4 0 3]
   [2 0 4]
   [4 0 1]]

  [[0 3 0]
   [0 4 1]
   [0 1 4]]

  [[3 0 3]
   [4 1 3]
   [1 4 4]]

  [[0 3 4]
   [1 3 1]
   [4 4 1]]

  [[3 4 4]
   [3 1 3]
   [4 1 0]]

  [[4 4 3]
   [1 3 0]
   [1 0 4]]]


 [[[4 1 2]
   [0 2 4]
   [3 1 0]]

  [[1 2 0]
   [2 4 0]
   [1 0 1]]

  [[2 0 4]
   [4 0 1]
   [0 1 0]]

  [[0 4 1]
   [0 1 4]
   [1 0 0]]

  [[4 1 3]
   [1 4 4]
   [0 0 1]]

  [[1 3 1]
   [4 4 1]
   [0 1 0]]

  [[3 1 3]
   [4 1 0]
   [1 0 4]]

  [[1 3 0]
   [1 0 4]
   [0 4 4]]]


 [[[0 2 4]
   [3 1 0]
   [0 1 2]]

  [[2 4 0]
   [1 0 1]
   [1 2 1]]

  [[4 0 1]
   [0 1 0]
   [2 1 1]]

  [[0 1 4]
   [1 0 0]
   [1 1 3]]

  [[1 4 4]
   [0 0 1

# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 

# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [35]:
a = np.random.randint(0,5,(16,16))

n = 4
s = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], n), axis=0),
                                       np.arange(0, a.shape[1], n), axis=1)
print(s)

16x16 matrix:
[[2 0 1 3 1 0 3 3 4 2 3 3 0 4 0 0]
 [4 2 0 2 1 3 3 3 1 3 3 3 4 4 4 4]
 [2 2 1 0 0 1 4 1 1 2 2 1 1 3 1 1]
 [1 2 2 2 2 4 2 1 2 0 2 1 0 2 3 2]
 [1 1 3 3 3 1 3 4 1 2 1 3 0 4 0 2]
 [4 2 1 3 0 1 1 0 2 1 2 1 0 4 0 0]
 [3 0 0 0 3 1 2 4 4 0 2 1 3 1 3 0]
 [4 3 2 1 2 2 4 2 3 0 4 1 0 4 2 0]
 [1 3 2 3 3 4 3 0 1 0 4 4 2 1 4 0]
 [0 2 1 3 2 2 1 1 4 1 3 4 2 1 3 1]
 [2 2 4 4 3 4 3 0 3 4 2 2 3 1 3 1]
 [2 1 2 0 2 1 2 3 0 4 2 2 3 3 2 3]
 [4 1 4 0 1 1 3 1 1 0 1 4 4 0 1 1]
 [4 0 0 3 3 0 1 2 2 1 1 0 3 1 2 4]
 [1 2 3 2 4 0 4 2 4 3 1 0 0 0 1 1]
 [0 2 1 3 3 1 4 4 1 2 3 3 1 3 3 0]]
[[26 32 33 33]
 [31 33 28 23]
 [32 34 40 33]
 [30 34 27 25]]


# 88. How to implement the Game of Life using numpy arrays?

# 89. How to get the n largest values of an array

In [53]:
a = np.arange(100)
n = 7
print (a[np.argsort(a)[-n:]])

[93 94 95 96 97 98 99]


# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [55]:
x = np.array([1,2,3])
y = np.array([4,5])
result = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
print(result)

[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]]


# 91. How to create a record array from a regular array? 

In [58]:
a = np.array([("A", 88.5, 90),
                 ("B", 87, 99),
             ("C", 85.5, 91)])
print("Original arrays:")
print(a)
print("\nRecord array;")
result = np.core.records.fromarrays(a.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['A' '88.5' '90']
 ['B' '87' '99']
 ['C' '85.5' '91']]

Record array;
[(b'A', 88.5, 90) (b'B', 87. , 99) (b'C', 85.5, 91)]


# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [68]:
Z = np.random.randint(500)
print(np.power(Z,3))
print(Z**3)
print(Z*Z*Z)

11089567
11089567
11089567


# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [67]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
print(f"{a}\n{b}")
c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[[3 3 1]
 [3 1 2]
 [3 1 2]
 [2 0 3]
 [0 3 2]
 [2 3 0]
 [2 1 4]
 [0 3 4]]
[[0 4]
 [3 0]]
[3 4 5 7]


# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [6]:
nums = np.random.randint(0,4,(10,3))
print(nums)
new_nums = np.logical_and.reduce(nums[:,1:] == nums[:,:-1], axis=1)
result = nums[~new_nums]
print("Rows with unequal values:")
print(result)

[[1 0 0]
 [1 3 0]
 [0 3 3]
 [3 2 0]
 [2 2 3]
 [0 1 0]
 [0 0 1]
 [3 3 3]
 [0 3 3]
 [0 2 2]]
Rows with unequal values:
[[1 0 0]
 [1 3 0]
 [0 3 3]
 [3 2 0]
 [2 2 3]
 [0 1 0]
 [0 0 1]
 [0 3 3]
 [0 2 2]]


# 95. Convert a vector of ints into a matrix binary representation 

In [7]:
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 96. Given a two dimensional array, how to extract unique rows?

In [75]:
a = np.random.randint(0,5,(6,3))
print(a)
print('\n')
unique_rows = np.unique(a, axis=0)
print(unique_rows)

[[3 4 2]
 [3 1 4]
 [3 2 3]
 [1 4 4]
 [1 2 4]
 [4 4 2]]


[[1 2 4]
 [1 4 4]
 [3 1 4]
 [3 2 3]
 [3 4 2]
 [4 4 2]]


# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [78]:
a= np.random.randint(0,4,10)
b = np.random.randint(0,5,10)

print(np.einsum('i->', a))       
print(np.einsum('i,i->i', a, b)) 
print(np.einsum('i,i', a, b))   
print(np.einsum('i,j->ij', a, b))   

14
[ 0  2  0  2  0 12  9  2  0 12]
39
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  2  4  1  0  4  3  2  0  4]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  4  8  2  0  8  6  4  0  8]
 [ 0  2  4  1  0  4  3  2  0  4]
 [ 0  6 12  3  0 12  9  6  0 12]
 [ 0  6 12  3  0 12  9  6  0 12]
 [ 0  2  4  1  0  4  3  2  0  4]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  6 12  3  0 12  9  6  0 12]]


# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).